### PR TITLE
Fix: promise evaluation

### LINKED ISSUE #122: Forcing closures should update environment
I realized that when forcing symbols (as is the case for function formals), they aren't actually evaluated, updating the symbol in the environment.

Take for instance:

```r
f <- function(a) { a; a; NULL }
f(print("forcing 'a'!"))
# [1] "forcing 'a'!"
# [1] "forcing 'a'!"
# NULL
```

The result of forcing the closure doesn't update the value of `a`. 

It's worth noting, that we _also_ need to maintain the un-evaluated closure expression for `substitute`:

```r
f <- function(a) { a; print(substitute(a)); NULL }
f(print("forcing 'a'!"))
# [1] "forcing 'a'!"
# print("forcing 'a'!")
# NULL
```

I'm not exactly sure on the right path forward here. This could be solved by:

1. function environments having a special place for storing arguments, so that we can always retrieve argument expressions even after they're forced. When a closure is evaluated, we simply update the `Environment` to store the new `Obj`, replacing the closure.
2. Closures could have an extra `Option<Obj>` field that starts as `None` and becomes an `Obj` after evaluation, meaning that all closures could cache their result.
3. We grab parameters from the last call on the call stack for `substitute()` and handle closures separately. 

---

I think `Closure` should probably be renamed to `Promise`, though there might be other closure-like use cases.

### PR DESCRIPTION
**Pull request by dgkf**
Closes #122

Fix: Saves result of forcing promise back into environment, instead of re-evaluating it every time.

Chore: Renames `Closure` to `Promise`. Maybe eventually there will be a need for both, but for now I think `Promise` is a better indication of what this represents. A `Closure` might be better represented by a function anyways (I think internally R refers to its functions as "closures" anyways since they always capture their environments).

### CODE REVIEW

File: src/lang.rs [hunk 1]
```diff
@@ -845,20 +845,25 @@ impl Context for CallStack {
...
-            }
+            let Some(value) = env.values.borrow_mut().get(&name).cloned() else {
+                // if not found, search through parent if available
+                if let Some(parent) = &env.parent {
+                    env = parent.clone();
+                    continue;
+                } else {
+                    break;
+                }
+            };
```
Comment (dgkf) [inline src/lang.rs:856]: @sebffischer emphasizing for awareness since you're thinking critically about the reference counting and mutability of objects.

This is how values are retrieved from an environment. Note that currently all values are _always `.cloned()`_ when they're accessed in an environment. This means that doing something as simple as:

```r
a <- 1
b <- a
c <- b
```

Produces three copies of the same data, despite no mutations. This is a known issue, just something I haven't addressed yet. 

I always imagined objects would need some sort of global reference counting at some point. Perhaps what is now `Obj` should likewise be converted into `ObjType` and we should have a similar pattern such as `Obj<Rc<ObjType<...>>>`.

This starts to look a tad redundant with the current vector stuff. 

Frankly, I think it's good to get the vectors sorted out in isolation. There's enough complexity there to really stress-test a concept. At some point we'll have to circle back and develop that idea into something more universal.
